spring:
  # 配置redis
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 10s
      lettuce:
        shutdown-timeout: 1s
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5
          max-wait: 5s
      password: Admin123!

  # 为openfeign添加hc5连接池支持
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

logging:
  config: classpath:logback-spring-new.xml
  level:
    com:
      alibaba:
        nacos: DEBUG

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true